// slm-manager/frontend/src/components/Logs.jsx
import React, { useRef, useEffect } from 'react'

const go = window.go?.main?.App

export default function Logs({ logs, onClear }) {
  const scrollRef = useRef(null)

  // Auto-scroll to bottom
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [logs])

  const openFolder = () => go?.OpenLogsFolder()

  return (
    <div style={styles.container}>
      {/* Actions */}
      <div style={styles.header}>
        <span style={styles.title}>Service Logs</span>
        <div style={styles.actions}>
          <button className="btn btn-sm" onClick={onClear}>Clear</button>
          <button className="btn btn-sm" onClick={openFolder}>Open Folder</button>
        </div>
      </div>

      {/* Log viewer */}
      <div ref={scrollRef} style={styles.viewer}>
        {logs.length === 0 ? (
          <div style={styles.empty}>No logs yet...</div>
        ) : (
          logs.map((log, i) => (
            <div key={i} style={{ ...styles.line, ...(log.type === 'error' ? styles.error : {}) }}>
              <span style={styles.time}>{log.time.toLocaleTimeString()}</span>
              <span style={styles.msg}>{log.msg}</span>
            </div>
          ))
        )}
      </div>
    </div>
  )
}

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  title: {
    fontSize: '15px',
    fontWeight: 500,
  },
  actions: {
    display: 'flex',
    gap: '8px',
  },
  viewer: {
    flex: 1,
    background: '#0d0d12',
    borderRadius: '4px',
    padding: '12px',
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
    overflow: 'auto',
    maxHeight: 'calc(100vh - 140px)',
  },
  empty: {
    color: 'var(--text-secondary)',
    fontStyle: 'italic',
  },
  line: {
    display: 'flex',
    gap: '12px',
    padding: '2px 0',
    borderBottom: '1px solid rgba(255,255,255,0.03)',
  },
  error: {
    color: 'var(--error)',
  },
  time: {
    color: 'var(--text-secondary)',
    flexShrink: 0,
  },
  msg: {
    wordBreak: 'break-word',
  },
}

// slm-manager/frontend/src/components/Logs.svelte
<script>
  export let logs = [];

  function clearLogs() {
    logs = [];
  }

  async function openLogsFolder() {
    await window.go.main.App.OpenLogsFolder();
  }
</script>

<div class="logs-container">
  <div class="header">
    <h2>Logs</h2>
    <div class="actions">
      <button class="btn secondary" on:click={clearLogs}>Clear</button>
      <button class="btn secondary" on:click={openLogsFolder}>Open Logs Folder</button>
    </div>
  </div>

  <div class="log-viewer">
    {#if logs.length === 0}
      <p class="empty">No logs yet...</p>
    {:else}
      {#each logs as log}
        <div class="log-entry" class:error={log.error}>
          <span class="time">{new Date(log.time).toLocaleTimeString()}</span>
          <span class="message">{log.message}</span>
        </div>
      {/each}
    {/if}
  </div>
</div>

<style>
  .logs-container {
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
  }

  h2 {
    font-size: 1.3rem;
    font-weight: 600;
  }

  .actions {
    display: flex;
    gap: 0.5rem;
  }

  .log-viewer {
    flex: 1;
    background: #0a0a0f;
    border-radius: 8px;
    padding: 1rem;
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
    font-size: 0.85rem;
    overflow-y: auto;
    max-height: calc(100vh - 200px);
  }

  .empty {
    color: var(--text-secondary);
    font-style: italic;
  }

  .log-entry {
    display: flex;
    gap: 1rem;
    padding: 0.25rem 0;
    border-bottom: 1px solid rgba(255, 255, 255, 0.03);
  }

  .log-entry.error {
    color: var(--error);
  }

  .time {
    color: var(--text-secondary);
    flex-shrink: 0;
  }

  .message {
    word-break: break-word;
  }

  .btn {
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 500;
    font-size: 0.9rem;
  }

  .btn.secondary {
    background: rgba(255, 255, 255, 0.1);
    color: var(--text-primary);
  }

  .btn:hover {
    filter: brightness(1.1);
  }
</style>
